# Generated by Django 2.2.12 on 2020-04-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_key',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
