# Generated by Django 2.2.12 on 2020-04-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tutorial_tutorial_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='tut_tut',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
